### ISSUE TITLE
Issue with component name

### ISSUE THREAD

**Issue by fonimus** [adeo/turbine-deploy-action#10]
Hello, I am using this deploy action for turbine, but the component name is re-written (cf image) ; cdp-sao--xxx becomes cdp-sao- (without double --)

![Capture d’écran 2021-06-25 à 11 33 05](https://user-images.githubusercontent.com/26186612/123404947-a6d37f80-d5a9-11eb-818a-7fc364fd6b15.png)

Do you have any idea why ?

Thanks !

**Comment by denouche** [comment]
Hello! can you send me the repo name ?

**Comment by fonimus** [comment]
https://github.com/adeo/cdp-sao--seller-delivery-repository
Example of failure : https://github.com/adeo/cdp-sao--seller-delivery-repository/runs/2952328302?check_suite_focus=true
